# Generated by Django 3.2 on 2022-07-26 21:50

from django.db import migrations


def filling_price_field(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all().iterator():
        for order_item in order.item.all().iterator():
            product = Product.objects.get(pk=order_item.product_id)
            order_item.price = product.price
            order_item.save()


def move_backward(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all().iterator():
        order_item.price = 100
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(filling_price_field, move_backward)
    ]
