# Generated by Django 3.2 on 2022-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Курьер выехал', 'Курьер выехал'), ('Собирается', 'Собирается'), ('Выполнен', 'Выполнен')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Адрес доставки'),
        ),
    ]
