# Generated by Django 3.2 on 2022-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220727_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Собирается', 'Собирается'), ('Выполнен', 'Выполнен'), ('Курьер выехал', 'Курьер выехал'), ('Принят', 'Принят')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
