# Generated by Django 3.2 on 2022-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220727_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('На сайте', 'На сайте'), ('При получении', 'При получении')], db_index=True, default='На сайте', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Собирается', 'Собирается'), ('Курьер выехал', 'Курьер выехал'), ('Выполнен', 'Выполнен')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
