# Generated by Django 3.2 on 2022-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220731_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('На сайте', 'На сайте'), ('При получении', 'При получении')], db_index=True, default='На сайте', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Готовится', 'Готовится'), ('Курьер выехал', 'Курьер выехал'), ('Выполнен', 'Выполнен'), ('Принят', 'Принят')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
