# Generated by Django 3.2 on 2022-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220917_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Курьер выехал', 'Курьер выехал'), ('Выполнен', 'Выполнен')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
