# Generated by Django 3.2 on 2022-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220917_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_preparing_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Курьер выехал', 'Курьер выехал'), ('Выполнен', 'Выполнен'), ('Готовится', 'Готовится'), ('Принят', 'Принят')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
