# Generated by Django 3.2 on 2022-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('При получении', 'При получении'), ('На сайте', 'На сайте')], db_index=True, default='При получении', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Выполнен', 'Выполнен'), ('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Курьер выехал', 'Курьер выехал')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
