# Generated by Django 3.2 on 2022-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20220917_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Курьер выехал', 'Курьер выехал'), ('Выполнен', 'Выполнен'), ('Готовится', 'Готовится')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
