# Generated by Django 3.2 on 2022-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('На сайте', 'На сайте'), ('При получении', 'При получении')], db_index=True, default='При получении', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Курьер выехал', 'Курьер выехал'), ('Готовится', 'Готовится'), ('Выполнен', 'Выполнен')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
