# Generated by Django 3.2 on 2022-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20220917_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Выполнен', 'Выполнен'), ('Принят', 'Принят'), ('Курьер выехал', 'Курьер выехал'), ('Готовится', 'Готовится')], db_index=True, default='Принят', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
