# Generated by Django 3.2 on 2022-10-04 22:12

from django.db import migrations


def copy_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')
    for order_item in OrderItem.objects.all().iterator():
        order_item.price = Product.objects.get(
            name=order_item.product.name).price
        order_item.save()


def move_backward(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all().iterator():
        order_item.price = 0
        order_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0060_auto_20221002_0027'),
    ]

    operations = [
        migrations.RunPython(copy_prices)
    ]
