# Generated by Django 3.2 on 2022-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'lon', 'address')},
        ),
    ]
