# Generated by Django 3.2 on 2022-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
    ]
