# Generated by Django 3.2 on 2022-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20220917_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
